# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/qtresources/SearchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SearchDialog(object):
    def setupUi(self, SearchDialog):
        SearchDialog.setObjectName("SearchDialog")
        SearchDialog.resize(360, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchDialog.sizePolicy().hasHeightForWidth())
        SearchDialog.setSizePolicy(sizePolicy)
        SearchDialog.setMinimumSize(QtCore.QSize(360, 200))
        SearchDialog.setMaximumSize(QtCore.QSize(500, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearchDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SearchDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditSearch = QtWidgets.QLineEdit(SearchDialog)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout_4.addWidget(self.lineEditSearch)
        self.buttonStartSearch = QtWidgets.QPushButton(SearchDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStartSearch.sizePolicy().hasHeightForWidth())
        self.buttonStartSearch.setSizePolicy(sizePolicy)
        self.buttonStartSearch.setMinimumSize(QtCore.QSize(30, 0))
        self.buttonStartSearch.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonStartSearch.setDefault(True)
        self.buttonStartSearch.setObjectName("buttonStartSearch")
        self.horizontalLayout_4.addWidget(self.buttonStartSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidgetResults = QtWidgets.QListWidget(SearchDialog)
        self.listWidgetResults.setObjectName("listWidgetResults")
        self.horizontalLayout_2.addWidget(self.listWidgetResults)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkboxCase = QtWidgets.QCheckBox(SearchDialog)
        self.checkboxCase.setObjectName("checkboxCase")
        self.verticalLayout_2.addWidget(self.checkboxCase)
        self.checkboxWholeWord = QtWidgets.QCheckBox(SearchDialog)
        self.checkboxWholeWord.setObjectName("checkboxWholeWord")
        self.verticalLayout_2.addWidget(self.checkboxWholeWord)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonDeleteResults = QtWidgets.QPushButton(SearchDialog)
        self.buttonDeleteResults.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/television_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDeleteResults.setIcon(icon1)
        self.buttonDeleteResults.setCheckable(False)
        self.buttonDeleteResults.setFlat(False)
        self.buttonDeleteResults.setObjectName("buttonDeleteResults")
        self.verticalLayout_3.addWidget(self.buttonDeleteResults)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(SearchDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.buttonBox = QtWidgets.QDialogButtonBox(SearchDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(SearchDialog)
        self.buttonBox.clicked['QAbstractButton*'].connect(SearchDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SearchDialog)

    def retranslateUi(self, SearchDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchDialog.setWindowTitle(_translate("SearchDialog", "Suche"))
        self.buttonStartSearch.setText(_translate("SearchDialog", ">"))
        self.checkboxCase.setText(_translate("SearchDialog", "Groß-/Kleinschreibung beachten"))
        self.checkboxWholeWord.setText(_translate("SearchDialog", "Einzelwörter suchen"))
        self.buttonDeleteResults.setText(_translate("SearchDialog", "Suchergebnisse entfernen"))

import icons_search_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchDialog = QtWidgets.QDialog()
    ui = Ui_SearchDialog()
    ui.setupUi(SearchDialog)
    SearchDialog.show()
    sys.exit(app.exec_())

